export const aiReferences = {
  metrics: {
    label: "NVIDIA / INFERENCE METRICS",
    url: "https://docs.nvidia.com/nim/benchmarking/llm/latest/metrics.html",
    note: "Definitions for TTFT, inter-token latency, end-to-end latency, and token throughput.",
  },
  serving: {
    label: "VLLM / PRODUCTION METRICS",
    url: "https://docs.vllm.ai/en/latest/usage/metrics/",
    note: "Observable queue, prefill, decode, running-request, and KV-cache signals.",
  },
  batching: {
    label: "HUGGING FACE / CONTINUOUS BATCHING",
    url: "https://huggingface.co/docs/transformers/main/en/serving#continuous-batching",
    note: "How active requests can be grouped and interleaved while finished sequences leave the batch.",
  },
  pagedAttention: {
    label: "PAGEDATTENTION PAPER",
    url: "https://arxiv.org/abs/2309.06180",
    note: "The vLLM paper on paged KV-cache memory management and serving throughput.",
  },
  kvCache: {
    label: "HUGGING FACE / KV CACHE",
    url: "https://huggingface.co/docs/transformers/main/cache_explanation",
    note: "Why autoregressive decoding reuses stored attention key/value state.",
  },
  prefixCache: {
    label: "VLLM / AUTOMATIC PREFIX CACHING",
    url: "https://docs.vllm.ai/en/stable/examples/features/automatic_prefix_caching/",
    note: "Reusing KV blocks when later prompts share the same prefix.",
  },
  autoscaling: {
    label: "KUBERNETES / HORIZONTAL AUTOSCALING",
    url: "https://kubernetes.io/docs/concepts/workloads/autoscaling/horizontal-pod-autoscale/",
    note: "Metric-driven replica changes, readiness, and startup stabilization.",
  },
  routing: {
    label: "ROUTELLM PAPER",
    url: "https://arxiv.org/abs/2406.18665",
    note: "Routing between stronger and weaker model tiers to balance cost and preference-derived quality.",
  },
};

export const AI_AUTOSCALE_PHASES = ["NORMAL", "SPIKE", "TRIGGERED", "MODEL LOADING", "READY", "RECOVERED"];

const addition = (name, why, improves, costs) => ({ name, why, improves, costs });

export const aiStages = [
  {
    id: "one-worker",
    number: "01",
    trafficLabel: "0.25 req/s",
    title: "One model server",
    eyebrow: "FOUNDATION / INFERENCE LIFECYCLE",
    scenario: "A small internal tool sends one short request at a time. One API and one model worker have abundant headroom.",
    principle: "Simple is enough for this workload. Learn the request lifecycle before introducing serving infrastructure.",
    question: "What should we add?",
    answer: "Nothing yet. Trace one request first.",
    workload: { requestRate: 0.25, concurrency: 1, promptTokens: 128, outputTokens: 64 },
    architecture: { workers: 1 },
    metricKeys: ["traffic", "ttft", "itl", "outputTps", "gpuUtil", "gpuMemory"],
    reference: "metrics",
    addition: addition("NO NEW INFRASTRUCTURE", "The current workload fits comfortably on one worker.", ["Fast iteration", "Low cost", "Clear mental model"], ["One failure domain", "Little burst headroom"]),
  },
  {
    id: "traffic",
    number: "02",
    trafficLabel: "12 req/s",
    title: "Requests start waiting",
    eyebrow: "CONSTRAINT / SINGLE-WORKER CAPACITY",
    scenario: "Concurrent requests arrive faster than the single model worker can complete prompt processing and generation.",
    principle: "A larger waiting set raises time to first token even when decode speed for an admitted request is unchanged.",
    question: "Requests arrive faster than the worker can serve them. What would you change first?",
    workload: { requestRate: 12, concurrency: 18, promptTokens: 512, outputTokens: 128 },
    architecture: { workers: 1 },
    metricKeys: ["traffic", "ttft", "p95", "gpuUtil", "active", "queueDepth"],
    reference: "serving",
    decisions: [
      {
        id: "explicit-queue",
        label: "Add an inference queue",
        effect: "Bounded admission + backpressure",
        recommended: true,
        patch: { queue: true },
        outcome: "Requests now wait in an explicit, observable queue. Bursts are controlled, but service capacity has not increased.",
        addition: addition("INFERENCE QUEUE", "Uncontrolled concurrency was pushing work directly at one constrained worker.", ["Backpressure", "Scheduling point", "Burst absorption"], ["Queue wait", "Capacity still unchanged", "Overflow policy required"]),
      },
      {
        id: "early-worker",
        label: "Add another GPU worker",
        effect: "Immediate capacity, higher cost",
        patch: { workers: 2, scheduler: true },
        outcome: "A second worker adds real capacity and lowers waiting. It also doubles the worker cost before admission and scheduling policy are explicit.",
      },
      {
        id: "early-batch",
        label: "Increase batch size",
        effect: "More shared execution",
        patch: { batching: "static", batchSize: 6 },
        outcome: "Static batching can improve useful GPU work, but requests may wait for batch formation and uneven sequence lengths waste slots.",
      },
      {
        id: "larger-model",
        label: "Use a larger model",
        effect: "Capability proxy up, compute up",
        patch: { routingStrategy: "always-large" },
        outcome: "Capability may improve, but the larger educational model consumes more compute and memory. It worsens this throughput constraint.",
      },
    ],
  },
  {
    id: "queue",
    number: "03",
    trafficLabel: "QUEUE GROWS",
    title: "A queue is not capacity",
    eyebrow: "CONSTRAINT / ARRIVAL > SERVICE",
    scenario: "The queue protects the worker during a burst, but sustained arrivals still exceed the service rate. The backlog keeps growing.",
    principle: "A queue buys control and time; it does not create inference compute.",
    question: "What actually removes a persistent backlog?",
    workload: { requestRate: 12, concurrency: 24, promptTokens: 512, outputTokens: 128, backlog: 36 },
    architecture: { workers: 1, queue: true },
    metricKeys: ["traffic", "capacity", "queueDepth", "queueWait", "ttft", "throughput"],
    reference: "serving",
    decisions: [
      {
        id: "worker-pool",
        label: "Add GPU workers",
        effect: "Scheduler + 3 workers",
        recommended: true,
        patch: { workers: 3, scheduler: true },
        outcome: "Aggregate service capacity now exceeds arrivals. The scheduler can drain the backlog across healthy workers.",
        addition: addition("SCHEDULER + WORKER POOL", "The explicit queue exposed a durable capacity deficit.", ["Higher throughput", "Lower queue wait", "Failure options"], ["Cost index increases", "Scheduling complexity", "Model placement constraints"]),
      },
      {
        id: "bigger-queue",
        label: "Make the queue larger",
        effect: "More waiting room",
        patch: { queueCapacity: 2400 },
        outcome: "More requests can wait before rejection, but the arrival/service imbalance is identical. Waiting time continues to grow.",
      },
      {
        id: "longer-timeout",
        label: "Raise client timeout",
        effect: "Clients wait longer",
        patch: {},
        outcome: "Fewer clients may abandon the request, but no additional tokens are generated per second and the backlog remains.",
      },
      {
        id: "queue-large-model",
        label: "Move to a larger model",
        effect: "More work per request",
        patch: { routingStrategy: "always-large" },
        outcome: "The quality proxy rises, but capacity falls and the queue grows faster. This is a product trade-off, not a scaling fix.",
      },
    ],
    checkpoint: {
      question: "Why doesn't adding a queue permanently solve insufficient GPU capacity?",
      options: [
        { id: "rate", label: "Arrival can still exceed service rate", correct: true, explanation: "Exactly. A queue stores work; only more effective service capacity can drain a sustained backlog." },
        { id: "tokens", label: "Queues delete output tokens", explanation: "The queue should preserve admitted work. Token count is not why backlog grows." },
        { id: "network", label: "The user network becomes slower", explanation: "The measured constraint is inside inference service capacity, before response delivery." },
      ],
    },
  },
  {
    id: "workers",
    number: "04",
    trafficLabel: "3 WORKERS",
    title: "Horizontal inference capacity",
    eyebrow: "RESPONSE / WORKER POOL",
    scenario: "Three independent workers now accept scheduled requests. Representative traffic fans out while the queue drains.",
    principle: "Horizontal serving increases aggregate capacity and resilience, but worker cost rises with it.",
    question: "What did horizontal scaling buy us?",
    answer: "Capacity and routing options—at a higher cost index.",
    workload: { requestRate: 12, concurrency: 24, promptTokens: 512, outputTokens: 128 },
    architecture: { workers: 3, queue: true, scheduler: true },
    metricKeys: ["traffic", "capacity", "queueDepth", "ttft", "workers", "cost"],
    reference: "serving",
    addition: addition("THREE GPU WORKERS", "One worker could not drain the admitted request rate.", ["Aggregate throughput", "Lower TTFT", "Rerouting options"], ["3× normalized worker cost", "Placement and health checks", "Large models may need tensor or pipeline parallelism across GPUs"]),
  },
  {
    id: "batching",
    number: "05",
    trafficLabel: "BATCH TOKENS",
    title: "Keep useful work on the GPU",
    eyebrow: "CONSTRAINT / SCHEDULING EFFICIENCY",
    scenario: "Variable-length requests leave execution slots underused when they are served sequentially or held in a rigid static batch.",
    principle: "Continuous batching admits new work as sequences finish. It generally improves aggregate throughput, while policy and waiting still affect latency.",
    question: "How should variable-length sequences share execution capacity?",
    workload: { requestRate: 20, concurrency: 48, promptTokens: 512, outputTokens: 160, backlog: 24 },
    architecture: { workers: 3, queue: true, scheduler: true, batching: "none", batchSize: 1 },
    metricKeys: ["throughput", "capacity", "gpuUtil", "ttft", "queueDepth", "costEfficiency"],
    reference: "batching",
    decisions: [
      {
        id: "continuous",
        label: "Continuous batching",
        effect: "Join and leave between steps",
        recommended: true,
        patch: { batching: "continuous", batchSize: 12 },
        outcome: "Finished sequences release slots and waiting requests can join later iterations. Useful throughput rises, with a small scheduling contribution to TTFT.",
        addition: addition("CONTINUOUS BATCHING", "Variable sequence lengths were leaving shared execution capacity idle.", ["GPU occupancy", "Aggregate throughput", "Cost efficiency"], ["Scheduler complexity", "Latency/throughput tuning", "Memory admission limits"]),
      },
      {
        id: "static",
        label: "Static batching",
        effect: "Process a fixed group",
        patch: { batching: "static", batchSize: 8 },
        outcome: "A fixed batch improves throughput over strictly sequential work, but completed sequences can leave unused slots until the group ends.",
      },
      {
        id: "batch-worker",
        label: "Add another worker",
        effect: "Capacity without scheduler efficiency",
        patch: { workers: 4 },
        outcome: "Capacity rises, but each worker still uses its execution slots inefficiently. Cost grows faster than useful throughput.",
      },
      {
        id: "short-output",
        label: "Limit output length",
        effect: "Less decode work",
        patch: {},
        outcome: "A product limit can reduce work and cost, but it changes the response contract rather than improving the serving engine.",
      },
    ],
    checkpoint: {
      question: "Why can more aggressive batching improve throughput but hurt latency?",
      options: [
        { id: "wait", label: "Requests may wait for scheduling opportunities", correct: true, explanation: "Right. Sharing execution improves aggregate work, but admission and batch policy can add waiting for an individual request." },
        { id: "quality", label: "Batches always lower model quality", explanation: "Batching changes execution scheduling, not inherently the model's learned capability." },
        { id: "cache", label: "Batching disables the KV cache", explanation: "Modern serving combines batching with KV-cache management; the two are not mutually exclusive." },
      ],
    },
  },
  {
    id: "kv-cache",
    number: "06",
    trafficLabel: "LONG CONTEXT",
    title: "Memory becomes the constraint",
    eyebrow: "CONSTRAINT / KV CACHE MEMORY",
    scenario: "Long prompts and many active sequences consume growing KV-cache memory even though batching improved compute utilisation.",
    principle: "Autoregressive decode reuses prior attention key/value state. That avoids repeated work, but the retained state consumes accelerator memory.",
    question: "Change prompt length and concurrency. Which resource reaches its limit first?",
    answer: "At long context and high concurrency, memory can become the admission constraint.",
    workload: { requestRate: 9, concurrency: 52, promptTokens: 4096, outputTokens: 256 },
    architecture: { workers: 4, queue: true, scheduler: true, batching: "continuous", batchSize: 12, kvCacheVisible: true, kvMemoryEfficiency: 1.15 },
    metricKeys: ["concurrency", "ttft", "gpuMemory", "kvCache", "active", "outputTps"],
    reference: "kvCache",
    addition: addition("EXPLICIT KV-CACHE BUDGET", "Decode should reuse previous token state, but active sequence state competes for finite memory.", ["Efficient autoregressive decode", "More useful generation work", "Measurable admission budget"], ["Memory grows with sequence state", "Eviction or recompute", "Long-context concurrency limits"]),
    checkpoint: {
      question: "Why does KV-cache pressure rise with concurrent long sequences?",
      options: [
        { id: "state", label: "Each active sequence retains token state", correct: true, explanation: "Exactly. More active tokens across more sequences require more key/value state to remain available for decode." },
        { id: "answers", label: "The cache stores finished answer text", explanation: "It stores attention key/value tensors used by inference, not a response-text database." },
        { id: "requests", label: "Every queued request is already decoded", explanation: "Waiting requests may not yet own a full active KV allocation; active admitted sequences drive this simplified pressure model." },
      ],
    },
  },
  {
    id: "streaming",
    number: "07",
    trafficLabel: "FIRST TOKEN",
    title: "Deliver tokens as they exist",
    eyebrow: "EXPERIENCE / RESPONSE DELIVERY",
    scenario: "The model generates tokens over time. A non-streaming client sees nothing until the full response has completed.",
    principle: "Streaming changes when output becomes visible. It does not inherently reduce prefill or decode compute.",
    question: "How should the API deliver generated output?",
    workload: { requestRate: 12, concurrency: 24, promptTokens: 512, outputTokens: 256 },
    architecture: { workers: 4, queue: true, scheduler: true, batching: "continuous", batchSize: 12, kvCacheVisible: true },
    metricKeys: ["ttft", "perceivedWait", "itl", "p95", "outputTps", "cost"],
    reference: "metrics",
    decisions: [
      {
        id: "stream",
        label: "Stream generated tokens",
        effect: "Show output after TTFT",
        recommended: true,
        patch: { streaming: true },
        outcome: "The first token becomes visible after TTFT and later tokens arrive at the decode cadence. Total generation work is unchanged.",
        addition: addition("STREAMING DELIVERY", "Users were waiting for the entire generation before seeing useful output.", ["Perceived responsiveness", "Progressive rendering", "Early user feedback"], ["Streaming protocol handling", "Partial-output UX", "Same model compute"]),
      },
      {
        id: "buffer",
        label: "Buffer the full response",
        effect: "One complete payload",
        patch: { streaming: false },
        outcome: "Delivery is operationally simpler, but the user-visible wait remains the full generation time rather than TTFT.",
      },
      {
        id: "stream-workers",
        label: "Add more workers",
        effect: "Capacity, not delivery",
        patch: { workers: 6 },
        outcome: "More workers help overloaded queues. They do not explain why an admitted response is hidden until generation finishes.",
      },
      {
        id: "shorter-generation",
        label: "Generate fewer tokens",
        effect: "Change product output limit",
        patch: {},
        outcome: "Shorter responses finish sooner, but changing the response contract is different from progressive delivery.",
      },
    ],
    checkpoint: {
      question: "Why can streaming feel faster without reducing total model compute?",
      options: [
        { id: "delivery", label: "The client sees tokens before generation ends", correct: true, explanation: "Correct. TTFT becomes the first visible wait, while decode continues until the final token." },
        { id: "skip", label: "Streaming skips the prefill phase", explanation: "Prefill still produces the state required before the first generated token." },
        { id: "parallel", label: "Every token is generated in parallel", explanation: "Autoregressive decode still produces later tokens from prior context; delivery is what changed here." },
      ],
    },
  },
  {
    id: "prefix-cache",
    number: "08",
    trafficLabel: "SHARED PREFIX",
    title: "Avoid repeated prefill work",
    eyebrow: "OPTIMISATION / PREFIX REUSE",
    scenario: "Many requests repeat a long shared system prefix but end with different user messages. The same prefix is being processed repeatedly.",
    principle: "Prefix caching can reuse matching prompt KV blocks. It is not a cache of final model responses.",
    question: "How should matching prompt prefixes reuse work?",
    workload: { requestRate: 14, concurrency: 32, promptTokens: 4096, outputTokens: 192 },
    architecture: { workers: 4, queue: true, scheduler: true, batching: "continuous", batchSize: 12, kvCacheVisible: true, streaming: true },
    metricKeys: ["ttft", "cachedPrompt", "prefixHit", "gpuUtil", "gpuMemory", "throughput"],
    reference: "prefixCache",
    decisions: [
      {
        id: "prefix",
        label: "Enable prefix caching",
        effect: "74% hit on 3,072 shared tokens",
        recommended: true,
        patch: { prefixCache: true, prefixHitRate: 0.74, repeatedPrefixTokens: 3072 },
        outcome: "Matching requests skip much of the repeated prefill computation. TTFT pressure falls, while cached blocks consume finite memory and may be evicted.",
        addition: addition("PREFIX CACHE", "A long identical prefix was recomputed across many different requests.", ["Less repeated prefill", "Potentially lower TTFT", "Compute efficiency"], ["Finite cache memory", "Eviction and match rules", "No benefit for unrelated prompts"]),
      },
      {
        id: "response-cache",
        label: "Cache complete responses",
        effect: "Only exact reusable answers",
        patch: {},
        outcome: "Response caching can be valid for deterministic, reusable outputs, but it is different from reusing internal prefix computation across distinct questions.",
      },
      {
        id: "prefix-worker",
        label: "Add another worker",
        effect: "More capacity, same repeated work",
        patch: { workers: 5 },
        outcome: "Capacity rises at additional cost, but every worker still recomputes the common prefix when no prefix state is reused.",
      },
      {
        id: "shorter-prefix",
        label: "Shorten the system prompt",
        effect: "Less input work",
        patch: {},
        outcome: "Prompt reduction is a strong product optimisation when possible, but it changes context rather than caching reusable work.",
      },
    ],
  },
  {
    id: "autoscaling",
    number: "09",
    trafficLabel: "20 → 120 RPS",
    title: "Scaling has a startup path",
    eyebrow: "CONSTRAINT / TRAFFIC SPIKE",
    scenario: "Normal traffic fits four workers. A sudden spike saturates them and queue depth rises before new model workers are ready.",
    principle: "An autoscaler can request capacity from utilisation, queue, active-request, or latency signals—but provisioning and model readiness take time.",
    question: "How should the service react to a burst that outlives the queue buffer?",
    workload: { requestRate: 20, concurrency: 40, promptTokens: 512, outputTokens: 128 },
    architecture: { workers: 4, queue: true, scheduler: true, batching: "continuous", batchSize: 12, kvCacheVisible: true, streaming: true, prefixCache: true, prefixHitRate: 0.55, repeatedPrefixTokens: 256 },
    metricKeys: ["traffic", "workers", "queueDepth", "ttft", "gpuUtil", "cost"],
    reference: "autoscaling",
    decisions: [
      {
        id: "autoscale",
        label: "Enable metric-driven autoscaling",
        effect: "Queue + GPU + latency signals",
        recommended: true,
        patch: { autoscaling: true },
        outcome: "The controller can request workers when sustained signals cross policy thresholds. Capacity arrives only after provisioning, model loading, warm-up, and readiness.",
        addition: addition("AUTOSCALER", "Sustained bursts exceed the warm worker pool.", ["Elastic capacity", "Queue recovery", "Demand-aware cost"], ["Delayed scale-out", "Metric and policy tuning", "Scale oscillation risk"]),
      },
      {
        id: "spare",
        label: "Keep ten workers warm",
        effect: "Immediate headroom",
        patch: { workers: 10 },
        outcome: "The spike is absorbed immediately, but the cost index remains high during normal traffic. Idle headroom can be an intentional latency choice.",
      },
      {
        id: "autoscale-queue",
        label: "Increase queue capacity",
        effect: "More burst buffer",
        patch: { queueCapacity: 3200 },
        outcome: "More work can wait, but TTFT rises while the original four workers remain the service-rate ceiling.",
      },
      {
        id: "scale-zero",
        label: "Scale workers to zero",
        effect: "Lowest idle cost",
        patch: { workers: 0, autoscaling: true },
        outcome: "Idle cost falls, but the first request must wait for the full worker startup and model-loading path. This is a latency/cost policy choice.",
      },
    ],
    checkpoint: {
      question: "Why might keeping idle GPU capacity be intentional?",
      options: [
        { id: "startup", label: "Warm workers avoid scale-out startup delay", correct: true, explanation: "Exactly. Spare capacity costs money, but it can protect TTFT while new workers would otherwise provision and load weights." },
        { id: "quality", label: "Idle GPUs make outputs more correct", explanation: "Warm capacity affects latency and availability, not the model's intrinsic answer quality." },
        { id: "tokens", label: "Idle workers pre-generate every answer", explanation: "They provide ready execution capacity; they do not know future requests." },
      ],
    },
  },
  {
    id: "routing",
    number: "10",
    trafficLabel: "MODEL TIERS",
    title: "Route for the product objective",
    eyebrow: "DECISION / COST • LATENCY • CAPABILITY",
    scenario: "Some requests are simple and latency-sensitive; others need a more capable but slower, costlier model tier.",
    principle: "A router encodes product policy. Misrouting can save cost while harming capability, so quality must be measured rather than assumed.",
    question: "Which routing policy best fits a mixed workload?",
    workload: { requestRate: 45, concurrency: 80, promptTokens: 768, outputTokens: 192, simpleRequestShare: 0.68 },
    architecture: { workers: 10, queue: true, scheduler: true, batching: "continuous", batchSize: 12, kvCacheVisible: true, streaming: true, prefixCache: true, prefixHitRate: 0.45, repeatedPrefixTokens: 256, autoscaling: true, routingStrategy: "always-large" },
    metricKeys: ["throughput", "ttft", "largeShare", "quality", "cost", "costEfficiency"],
    reference: "routing",
    decisions: [
      {
        id: "balanced",
        label: "Route by workload policy",
        effect: "Simple → fast / complex → capable",
        recommended: true,
        patch: { routingStrategy: "balanced" },
        outcome: "Most simple requests take the fast tier while complex work keeps access to the capable tier. Cost and latency fall, with measurable misrouting risk.",
        addition: addition("MODEL ROUTER", "One model tier was not optimal for every request objective.", ["Lower average cost", "Lower simple-request latency", "Policy control"], ["Quality evaluation required", "Router mistakes", "Tier-specific behavior"]),
      },
      {
        id: "always-large",
        label: "Always capable model",
        effect: "Highest quality proxy",
        patch: { routingStrategy: "always-large" },
        outcome: "The educational quality proxy is highest, but compute cost and latency are also highest and aggregate capacity is lower.",
      },
      {
        id: "always-fast",
        label: "Always fast model",
        effect: "Lowest cost and latency",
        patch: { routingStrategy: "always-fast" },
        outcome: "Capacity and cost improve sharply, but complex requests lose access to the capability they may require.",
      },
      {
        id: "tenant-policy",
        label: "Route only by tenant",
        effect: "Predictable commercial policy",
        patch: { routingStrategy: "balanced" },
        outcome: "Tenant policy can be legitimate, but it does not by itself account for task complexity or per-request latency objectives.",
      },
    ],
    checkpoint: {
      question: "Why can model routing reduce average inference cost?",
      options: [
        { id: "fit", label: "Not every request needs the costly tier", correct: true, explanation: "Correct. Eligible simple requests can use a cheaper tier while policy preserves capable-model access where needed." },
        { id: "free", label: "The router makes GPU execution free", explanation: "Routing changes the mix of model work; each selected model still consumes resources." },
        { id: "quality", label: "A quality proxy is universally objective", explanation: "Quality depends on tasks and evaluation. This Lab labels its score as a simplified educational proxy." },
      ],
    },
  },
  {
    id: "failure",
    number: "11",
    trafficLabel: "FAIL A WORKER",
    title: "Fallback changes the product",
    eyebrow: "FAILURE / REROUTE AND DEGRADE",
    scenario: "One model worker becomes unavailable. The scheduler removes it from service and the remaining pool absorbs eligible requests.",
    principle: "Redundancy preserves execution capacity. Model fallback can preserve availability, but behavior, capability, latency, and cost may change.",
    question: "The capable tier is impaired. How should eligible requests degrade?",
    workload: { requestRate: 76, concurrency: 110, promptTokens: 768, outputTokens: 192, simpleRequestShare: 0.68 },
    architecture: { workers: 10, queue: true, scheduler: true, batching: "continuous", batchSize: 12, kvCacheVisible: true, streaming: true, prefixCache: true, prefixHitRate: 0.45, repeatedPrefixTokens: 256, autoscaling: true, routingStrategy: "balanced" },
    metricKeys: ["workers", "queueDepth", "ttft", "availability", "quality", "cost"],
    reference: "routing",
    decisions: [
      {
        id: "fallback",
        label: "Use an eligible fallback tier",
        effect: "Availability over identical behavior",
        recommended: true,
        patch: { fallbackEnabled: true },
        outcome: "Eligible work continues on the fast tier. Availability improves, while the quality proxy and behavior contract explicitly change during degradation.",
        addition: addition("MODEL FALLBACK POLICY", "A primary model tier can become unavailable even while other inference capacity remains healthy.", ["Graceful degradation", "Higher availability", "Explicit eligibility rules"], ["Capability can change", "Behavior can change", "Fallback must be observable"]),
      },
      {
        id: "spare-failure",
        label: "Keep two spare workers",
        effect: "More warm redundancy",
        patch: { workers: 12 },
        outcome: "Warm redundancy preserves more capacity without changing model behavior, but raises the steady-state cost index.",
      },
      {
        id: "retry",
        label: "Retry the same tier",
        effect: "Preserve capability, add waiting",
        patch: {},
        outcome: "Retries may handle transient faults, but indefinite retry amplifies queue pressure and does not help a sustained tier outage.",
      },
      {
        id: "fast-only-failure",
        label: "Route everything to fast",
        effect: "Capacity up, capability proxy down",
        patch: { routingStrategy: "always-fast", fallbackEnabled: true },
        outcome: "The service stays responsive, but complex requests may receive a materially different capability level. Product policy must permit that change.",
      },
    ],
    checkpoint: {
      question: "What is the central trade-off of model fallback?",
      options: [
        { id: "behavior", label: "Availability rises while behavior may change", correct: true, explanation: "Exactly. A fallback can answer eligible requests, but capability and response characteristics may not match the unavailable tier." },
        { id: "identical", label: "Every model tier behaves identically", explanation: "If tiers were identical there would be little routing trade-off; capability and behavior differences must be explicit." },
        { id: "memory", label: "Fallback eliminates all GPU memory use", explanation: "The fallback model still consumes serving resources and maintains its own runtime state." },
      ],
    },
  },
];

export const recommendedAiDecision = (stage) => stage.decisions?.find((decision) => decision.recommended);
