export const roleplayIntentDefinitions = [
  {
    id: "identity",
    topicId: "stakeholder-role",
    priority: 8,
    examples: ["Who are you?", "Would you like to introduce yourself?", "What is your name?"],
    phrases: ["who are you", "introduce yourself", "your name", "who am i speaking to"],
    keywords: ["name", "identity", "introduce"],
    synonyms: [["who", "identity"], ["introduce", "introduction"]],
    questionWords: ["who", "what"],
    requiredSignals: [["who are you", "introduce yourself", "your name", "who am i speaking to"]],
    negativeSignals: ["responsible", "responsibilities", "involved", "day to day", "elaborate", "expand"],
  },
  {
    id: "role-responsibilities",
    topicId: "stakeholder-role",
    priority: 10,
    examples: [
      "Can you elaborate on your role?",
      "What are you responsible for?",
      "What does your role involve?",
      "Tell me more about what you do.",
    ],
    phrases: [
      "elaborate on your role",
      "expand on your role",
      "what your role involves",
      "what does your role involve",
      "what are you responsible for",
      "your responsibilities",
      "tell me more about what you do",
      "what do you do",
      "what does that involve",
    ],
    keywords: ["role", "responsible", "responsibilities", "involve", "elaborate", "expand", "duties"],
    synonyms: [["responsible", "responsibility", "duties"], ["elaborate", "expand", "explain"]],
    questionWords: ["what", "how"],
    negativeSignals: ["who are you", "your name", "sign off", "review content"],
  },
  {
    id: "role-involvement",
    topicId: "stakeholder-role",
    priority: 11,
    examples: [
      "How are you involved in Smart Rebook?",
      "What part do you play in the feature?",
      "How do you contribute to this work?",
    ],
    phrases: [
      "involved in smart rebook",
      "involved in the feature",
      "your involvement",
      "part do you play",
      "your part in",
      "contribute to the feature",
      "how are you involved",
    ],
    keywords: ["involved", "involvement", "contribute", "feature", "part"],
    synonyms: [["involved", "contribute", "participate"], ["feature", "product"]],
    questionWords: ["how", "what"],
    requiredSignals: [["involved", "involvement", "part do you play", "contribute"]],
  },
  {
    id: "role-day-to-day",
    topicId: "stakeholder-role",
    priority: 11,
    examples: [
      "What does your role cover day to day?",
      "What does that look like in practice?",
      "What do you normally do each day?",
    ],
    phrases: ["day to day", "day-to-day", "look like in practice", "normally do", "typical day", "daily contribution"],
    keywords: ["daily", "normally", "routine", "practice", "day"],
    synonyms: [["daily", "routine", "normally"], ["practice", "day to day"]],
    questionWords: ["what", "how"],
    requiredSignals: [["day to day", "look like in practice", "normally", "typical day", "daily"]],
  },
  {
    id: "role-authority",
    topicId: "stakeholder-role",
    priority: 9,
    examples: [
      "What decisions can you make?",
      "What are you able to approve?",
      "Who has authority over the feature?",
    ],
    phrases: ["decision making authority", "what decisions", "able to approve", "authority over", "what do you own", "who decides"],
    keywords: ["authority", "decision", "decide", "approve", "ownership", "own"],
    synonyms: [["authority", "approve", "decide"], ["own", "ownership"]],
    questionWords: ["what", "who"],
  },
  {
    id: "role-stakeholders",
    topicId: "stakeholder-role",
    priority: 8,
    examples: [
      "Who do you work with?",
      "Which colleagues support the feature?",
      "Who else is involved in your work?",
    ],
    phrases: ["who do you work with", "who else is involved", "colleagues do you work with", "teams do you work with", "stakeholders do you work with"],
    keywords: ["colleagues", "teams", "stakeholders", "work", "support"],
    synonyms: [["colleagues", "teams", "stakeholders", "people"]],
    questionWords: ["who", "which"],
    requiredSignals: [["work with", "who else", "colleagues", "teams", "stakeholders"]],
    negativeSignals: ["review", "sign off", "approve learning", "proof"],
  },
  {
    id: "opening",
    topicId: "opening",
    priority: 8,
    examples: [
      "Can we agree what we need to cover today?",
      "We have ten minutes, so can I outline the purpose of this meeting?",
      "What should we cover in our time together?",
    ],
    phrases: ["agenda", "time together", "cover today", "aim for this meeting", "purpose of this meeting", "outline the purpose", "ten minutes"],
    keywords: ["agenda", "meeting", "cover", "time", "purpose"],
    synonyms: [["agenda", "plan", "structure"], ["meeting", "conversation", "call"]],
    questionWords: ["what", "how"],
  },
  {
    id: "meeting-questions",
    topicId: "opening",
    priority: 10,
    examples: [
      "Do you have any questions before we begin?",
      "Is there anything you would like to ask before I start?",
    ],
    phrases: ["questions before we begin", "questions before i begin", "questions before i start", "anything you would like to ask", "anything from me before"],
    keywords: ["questions", "begin", "start"],
    synonyms: [["begin", "start"], ["questions", "ask"]],
    questionWords: ["do", "is"],
    requiredSignals: [["before we begin", "before i begin", "before i start", "anything from me"]],
  },
  {
    id: "booknest-context",
    topicId: "booknest-context",
    priority: 9,
    examples: ["What is BookNest?", "Can you tell me about BookNest and its core product?"],
    phrases: ["what is booknest", "tell me about booknest", "booknest core product", "existing booknest product", "what does booknest do"],
    keywords: ["booknest", "company", "product"],
    synonyms: [["company", "business", "product"]],
    questionWords: ["what", "how"],
    requiredSignals: [["booknest"]],
    negativeSignals: ["customer types", "which businesses", "smart rebook"],
  },
  {
    id: "customer-profile",
    topicId: "customer-profile",
    priority: 9,
    examples: [
      "What types of businesses use BookNest?",
      "Who are your typical customers?",
      "What is the BookNest customer base?",
    ],
    phrases: ["typical customers", "types of businesses", "kinds of businesses", "who uses booknest", "booknest customer base", "who are your customers"],
    keywords: ["businesses", "customers", "booknest", "salons", "clinics"],
    synonyms: [["businesses", "companies", "customers"], ["typical", "usual", "common"]],
    questionWords: ["who", "what", "which"],
    requiredSignals: [["booknest", "businesses", "typical customers", "your customers"]],
    negativeSignals: ["learning audience", "learners", "smart rebook users"],
  },
  {
    id: "learning-brief",
    topicId: "learning-brief",
    priority: 10,
    examples: [
      "What am I being asked to create?",
      "What should the short piece of learning achieve?",
      "Can you clarify the learning brief?",
    ],
    phrases: ["what am i creating", "asked to create", "learning brief", "course brief", "piece of learning", "short learning", "goal of the content"],
    keywords: ["brief", "learning", "course", "content", "create"],
    synonyms: [["brief", "scope"], ["learning", "training", "content", "course"]],
    questionWords: ["what", "how"],
  },
  {
    id: "purpose",
    topicId: "purpose",
    priority: 10,
    examples: [
      "Why was Smart Rebook created?",
      "What customer problem is the feature trying to solve?",
      "What do customers do today when a slot is cancelled?",
      "What is the expected customer and business benefit?",
    ],
    phrases: [
      "why was smart rebook created",
      "why smart rebook exists",
      "customer problem",
      "problem trying to solve",
      "what customers do today",
      "what customers have to do",
      "customers have to do",
      "what are customers doing today",
      "current workaround",
      "expected customer benefit",
      "business value",
      "why is it important",
      "why does it matter",
      "reason for the feature",
      "explain the purpose",
    ],
    keywords: ["why", "purpose", "problem", "workaround", "benefit", "value", "important", "matter", "created"],
    synonyms: [["purpose", "reason", "created"], ["problem", "difficulty", "challenge"], ["benefit", "value", "outcome"]],
    questionWords: ["why", "what", "how"],
  },
  {
    id: "audience",
    topicId: "audience",
    priority: 9,
    examples: [
      "Who is the learning intended for?",
      "Which customer roles will use Smart Rebook?",
      "Does this apply to all BookNest customers?",
    ],
    phrases: ["target audience", "who is this for", "who is it really for", "learning intended for", "intended users", "customer roles", "all booknest customers", "who will use smart rebook", "who are the learners"],
    keywords: ["audience", "learners", "users", "roles", "customers", "intended"],
    synonyms: [["audience", "learners", "users"], ["intended", "target", "aimed"]],
    questionWords: ["who", "which", "what"],
    requiredSignals: [["target audience", "who is this for", "who is it really for", "intended", "learners", "users", "customer roles", "all booknest"]],
    negativeSignals: ["types of businesses", "typical customers"],
  },
  {
    id: "prior-knowledge",
    topicId: "prior-knowledge",
    priority: 9,
    examples: [
      "What should learners already know?",
      "How much technical knowledge can we assume?",
      "Are there prerequisites?",
    ],
    phrases: ["already know", "prior knowledge", "current knowledge", "technical knowledge", "familiar with", "prerequisite", "prerequisites for the learner", "starting knowledge", "assume they know"],
    keywords: ["knowledge", "technical", "prerequisite", "familiar", "already", "assume"],
    synonyms: [["knowledge", "understanding", "experience"], ["prerequisite", "starting point"]],
    questionWords: ["what", "how"],
  },
  {
    id: "learning-outcomes",
    topicId: "learning-outcomes",
    priority: 9,
    examples: [
      "What should customers understand after the learning?",
      "What should a learner be able to do?",
      "What is the key takeaway?",
    ],
    phrases: ["learning outcome", "aim of the learning", "objective of the learning", "able to do", "need to understand", "key takeaway", "successful learner outcome", "after the learning"],
    keywords: ["outcome", "objective", "takeaway", "understand", "learn", "able"],
    synonyms: [["outcome", "objective", "takeaway"], ["understand", "know", "do"]],
    questionWords: ["what", "how"],
  },
  {
    id: "core-behaviour",
    topicId: "workflow",
    priority: 10,
    examples: [
      "How does Smart Rebook work from beginning to end?",
      "What happens after a cancellation?",
      "What triggers the Smart Rebook workflow?",
    ],
    phrases: ["how does smart rebook work", "what does smart rebook do", "end to end", "beginning to end", "complete workflow", "after a cancellation", "when someone cancels", "what triggers smart rebook"],
    keywords: ["workflow", "process", "cancellation", "cancel", "trigger", "work"],
    synonyms: [["workflow", "process", "steps"], ["cancellation", "cancelled", "cancels"], ["trigger", "start", "begin"]],
    questionWords: ["how", "what", "when"],
  },
  {
    id: "activation",
    topicId: "setup",
    priority: 10,
    examples: [
      "How do customers enable Smart Rebook?",
      "What setup is required?",
      "Who activates the feature?",
    ],
    phrases: ["enable smart rebook", "turn it on", "set it up", "setup required", "how is it configured", "who activates", "who would do that"],
    keywords: ["enable", "activation", "activate", "setup", "configure", "settings"],
    synonyms: [["enable", "activate", "turn on"], ["setup", "configure", "settings"]],
    questionWords: ["how", "what", "who"],
  },
  {
    id: "waitlist",
    topicId: "workflow",
    priority: 9,
    examples: [
      "How are waitlists created?",
      "Who can be added to a waitlist?",
      "How is the waitlist maintained?",
    ],
    phrases: ["waitlist created", "create a waitlist", "join the waitlist", "added to the waitlist", "who is on the waitlist", "maintain the waitlist", "populate the waitlist"],
    keywords: ["waitlist", "join", "added", "maintain", "populate", "consent"],
    synonyms: [["create", "make", "build"], ["join", "added", "enrol"]],
    questionWords: ["how", "who", "what"],
    requiredSignals: [["waitlist"]],
  },
  {
    id: "notification",
    topicId: "workflow",
    priority: 10,
    examples: [
      "What triggers the email?",
      "Who receives the notification?",
      "When is the customer communication sent?",
    ],
    phrases: ["triggers the email", "who receives the email", "who receives the notification", "when is the email sent", "customer communication", "email trigger"],
    keywords: ["email", "notification", "communication", "sent", "receives", "trigger"],
    synonyms: [["email", "message", "notification", "communication"], ["send", "sent", "receive"]],
    questionWords: ["what", "who", "when", "how"],
  },
  {
    id: "client-experience",
    topicId: "workflow",
    priority: 9,
    examples: [
      "What does the customer receive?",
      "What does the email look like?",
      "How does a client try to claim the slot?",
    ],
    phrases: ["what does the customer receive", "what does the client see", "email look like", "message contain", "claim button", "claim the slot", "customer experience", "client experience"],
    keywords: ["customer", "client", "receive", "see", "email", "claim", "button", "message"],
    synonyms: [["customer", "client", "recipient"], ["receive", "see", "shown"], ["claim", "take", "accept"]],
    questionWords: ["what", "how"],
    requiredSignals: [["receive", "see", "email", "message", "claim", "client experience", "customer experience"]],
  },
  {
    id: "multiple-responses",
    topicId: "edge-cases",
    priority: 10,
    examples: [
      "What happens if several people respond?",
      "What if two clients try to claim the slot at the same time?",
      "What does an unsuccessful respondent see?",
    ],
    phrases: ["multiple people respond", "more than one responds", "respond at once", "responds first", "already taken", "already been taken", "competing responses", "same time", "unsuccessful response"],
    keywords: ["multiple", "several", "competing", "same", "first", "already", "unsuccessful", "respond"],
    synonyms: [["multiple", "several", "more than one", "two"], ["respond", "claim", "accept"], ["same time", "simultaneously"]],
    questionWords: ["what", "who", "how"],
  },
  {
    id: "after-acceptance",
    topicId: "workflow",
    priority: 10,
    examples: [
      "What happens after someone accepts?",
      "What happens next once the slot is claimed?",
      "Does the successful client receive confirmation?",
    ],
    phrases: ["after acceptance", "after they accept", "after someone accepts", "once accepted", "once they claim", "successful client", "booking confirmation"],
    keywords: ["accept", "accepted", "claim", "confirmation", "successful"],
    synonyms: [["after", "next", "then"], ["accept", "claim", "take"], ["confirmation", "confirmed"]],
    questionWords: ["what", "how"],
  },
  {
    id: "errors",
    topicId: "edge-cases",
    priority: 9,
    examples: [
      "What commonly goes wrong?",
      "What mistakes or confusion should the learning address?",
      "Are there known limitations?",
      "Why might customers stop using it?",
    ],
    phrases: ["go wrong", "common mistake", "common confusion", "potential blocker", "known limitation", "stop using", "troubleshoot", "failure", "edge case"],
    keywords: ["error", "failure", "confusion", "mistake", "blocker", "limitation", "troubleshoot", "stop"],
    synonyms: [["error", "failure", "issue", "problem"], ["confusion", "mistake", "misunderstanding"], ["limitation", "constraint"]],
    questionWords: ["what", "why", "how"],
    negativeSignals: ["support", "escalate", "help centre", "raise a ticket"],
  },
  {
    id: "support",
    topicId: "support",
    priority: 9,
    examples: [
      "Where should customers go for support?",
      "How should a failed workflow be escalated?",
      "Can we signpost customers to help?",
    ],
    phrases: ["where should customers go for support", "signpost to support", "help centre", "help center", "raise a ticket", "contact for help", "support route", "how is it escalated", "account specific failure", "failure be escalated"],
    keywords: ["support", "help", "escalate", "ticket", "troubleshoot"],
    synonyms: [["support", "help", "assistance"], ["escalate", "ticket", "contact"]],
    questionWords: ["where", "how", "who", "what"],
  },
  {
    id: "success",
    topicId: "success",
    priority: 9,
    examples: [
      "How would you measure success?",
      "What would a successful customer look like after three months?",
      "Which adoption or support signals matter after launch?",
      "How would you know the learning worked?",
    ],
    phrases: ["measure success", "how would you know", "signs of success", "successful customer", "feature and learning are successful", "after three months", "support ticket changes", "adoption", "completion", "after launch", "learning worked"],
    keywords: ["measure", "metric", "success", "effective", "impact", "adoption", "completion", "tickets", "data", "analytics"],
    synonyms: [["measure", "metric", "signal", "indicator"], ["success", "effective", "worked", "impact"], ["adoption", "usage", "completion"]],
    questionWords: ["how", "what", "which"],
  },
  {
    id: "materials",
    topicId: "content-production",
    priority: 9,
    examples: [
      "What existing documentation is available?",
      "Can I use demos, screenshots or release notes?",
      "Which source materials can you provide?",
    ],
    phrases: ["existing documentation", "what documentation", "source material", "help article", "release notes", "demos and screenshots", "existing content", "assets available"],
    keywords: ["documentation", "documents", "screenshots", "demo", "materials", "assets", "article", "release"],
    synonyms: [["documentation", "documents", "materials", "assets"], ["screenshots", "demo", "release notes", "article"]],
    questionWords: ["what", "which"],
  },
  {
    id: "test-access",
    topicId: "content-production",
    priority: 10,
    examples: [
      "Is there a test environment available?",
      "Can I access a sandbox and test inbox?",
      "Can I try the feature safely?",
    ],
    phrases: ["test environment", "test instance", "sandbox", "test access", "try the feature", "test account", "test inbox", "product access"],
    keywords: ["test", "sandbox", "environment", "instance", "access", "inbox"],
    synonyms: [["test environment", "sandbox", "test instance"], ["access", "account", "try"]],
    questionWords: ["is", "can", "how", "what"],
  },
  {
    id: "signoff",
    topicId: "review-stakeholders",
    priority: 10,
    examples: [
      "Who should fact-check the content?",
      "Which SME reviews product accuracy?",
      "Who signs off the final learning?",
    ],
    phrases: ["sign off", "signoff", "fact check", "accuracy review", "who should review", "which sme", "review and approval", "proof the content", "final approval"],
    keywords: ["review", "reviewer", "approve", "approval", "accuracy", "signoff", "proof", "sme"],
    synonyms: [["review", "proof", "fact check"], ["approve", "signoff", "approval"], ["sme", "expert", "stakeholder"]],
    questionWords: ["who", "which", "how"],
  },
  {
    id: "timing",
    topicId: "review-stakeholders",
    priority: 8,
    examples: [
      "When is the feature launching?",
      "What dependencies affect the deadline?",
      "Is the final interface copy ready?",
    ],
    phrases: ["launch date", "when is it due", "go live", "release date", "target release", "what dependencies", "deadline", "final interface copy"],
    keywords: ["launch", "release", "deadline", "timeline", "dependency", "dependencies", "due"],
    synonyms: [["launch", "release", "go live"], ["deadline", "timeline", "due"], ["dependency", "blocker"]],
    questionWords: ["when", "what", "how"],
  },
  {
    id: "summary",
    topicId: "summary",
    priority: 11,
    examples: [
      "Can I summarise my understanding?",
      "Have I understood that correctly?",
      "Let me check I have got this right.",
    ],
    phrases: ["to summarise", "have i understood", "have i got that", "check my understanding", "does that sound right", "let me recap"],
    keywords: ["summarise", "recap", "understood", "understanding", "correctly", "right"],
    synonyms: [["summarise", "recap", "repeat"], ["understood", "understanding", "correct"]],
    questionWords: ["have", "does", "can"],
  },
  {
    id: "next-steps",
    topicId: "closing",
    priority: 10,
    examples: [
      "What are the agreed next steps?",
      "What should I send you after this meeting?",
      "Can we confirm our actions and owners?",
    ],
    phrases: ["next steps", "follow up", "send you", "come back to you", "another meeting", "actions from here", "agreed actions", "what happens after this meeting"],
    keywords: ["next", "follow", "actions", "owners", "send", "after"],
    synonyms: [["next steps", "actions", "follow up"], ["owner", "responsibility"]],
    questionWords: ["what", "who", "how"],
  },
  {
    id: "thanks",
    topicId: "closing",
    priority: 7,
    examples: ["Thank you for your time.", "Thanks, that was helpful.", "I appreciate you walking me through it."],
    phrases: ["thank you for your time", "thanks for your time", "thank you for walking me through", "that was helpful", "appreciate your help"],
    keywords: ["thank", "thanks", "appreciate", "helpful"],
    synonyms: [["thank", "thanks", "appreciate"]],
    questionWords: [],
  },
];

export const roleplayIntentById = Object.fromEntries(
  roleplayIntentDefinitions.map((intent) => [intent.id, intent]),
);
