export const scaleStages = [
  {
    id: "simple",
    number: "01",
    users: 10,
    trafficLabel: "~10 users",
    title: "The simple system",
    eyebrow: "START WITH ENOUGH",
    scenario: "A new product has a handful of users and almost no traffic. One application server and one database handle the workload comfortably.",
    question: "What should we add?",
    answer: "Nothing yet.",
    principle: "This architecture is enough. Complexity has a cost, so wait for a real constraint before introducing it.",
    architecture: {},
    workload: { requestsPerSecond: 2, readRatio: 0.76, staticShare: 0.18, expensiveWorkShare: 0.02, expensiveWorkMs: 160, geographicFactor: 0.35 },
    metricKeys: ["traffic", "p50", "p95", "apiUtil", "dbUtil", "errorRate"],
    addition: {
      name: "NO NEW INFRASTRUCTURE",
      why: "The current workload is far below available capacity.",
      improves: ["Fast delivery", "Low cost", "Easy operations"],
      costs: ["Limited headroom", "Single points of failure"],
    },
  },
  {
    id: "api-bottleneck",
    number: "02",
    users: 10000,
    trafficLabel: "100 → 1K → 10K",
    title: "The API bottleneck",
    eyebrow: "CONSTRAINT / COMPUTE",
    scenario: "Traffic rises sharply. The database still has headroom, but the single API process is spending nearly all its time serving requests.",
    question: "Your API server is overloaded. What would you change?",
    principle: "Increase capacity where the pressure actually is, then remove the single point of failure.",
    architecture: {},
    workload: { requestsPerSecond: 1320, readRatio: 0.78, staticShare: 0.18, expensiveWorkShare: 0.06, expensiveWorkMs: 180, geographicFactor: 0.6 },
    metricKeys: ["traffic", "p95", "p99", "apiUtil", "errorRate", "throughput"],
    decisions: [
      {
        id: "vertical-api",
        label: "Upgrade the server",
        effect: "1.65× API capacity",
        outcome: "A quick and valid relief valve. CPU and latency fall, but the application still has one failure domain and a finite scaling ceiling.",
        patch: { verticalMultiplier: 1.65 },
        addition: { name: "VERTICAL SCALING", why: "The current API needs immediate headroom.", improves: ["API CPU", "Short-term latency", "Deployment speed"], costs: ["Larger single point of failure", "Hardware ceiling", "Bigger replacement cost"] },
      },
      {
        id: "horizontal-api",
        label: "Add API instances",
        effect: "Load balancer + 3 APIs",
        outcome: "Capacity now grows horizontally and the load balancer spreads requests across independent stateless instances.",
        recommended: true,
        patch: { loadBalancer: true, apiInstances: 3 },
        addition: { name: "HORIZONTAL SCALING", why: "One API instance is saturated and is also a single point of failure.", improves: ["Compute capacity", "Availability", "Rolling changes"], costs: ["Load-balancer dependency", "Stateless application design", "More instances to observe"] },
      },
      {
        id: "early-cache",
        label: "Add Redis",
        effect: "72% repeated-read hit rate",
        outcome: "Database work falls, but the API is the saturated resource. Caching the data does not create more application compute.",
        patch: { cache: true, cacheHitRate: 0.72 },
        addition: { name: "EARLY CACHE", why: "Repeated reads can avoid database work.", improves: ["Database reads", "Hot-key latency"], costs: ["API bottleneck remains", "Invalidation", "Memory"] },
      },
      {
        id: "early-queue",
        label: "Add a queue",
        effect: "Move background work",
        outcome: "The synchronous path becomes a little lighter, but ordinary request handling still saturates the only API instance.",
        patch: { queue: true, workers: 2 },
        addition: { name: "EARLY QUEUE", why: "Background work can leave the request path.", improves: ["Async task latency", "Failure isolation"], costs: ["Core API pressure remains", "Retries", "Eventual processing"] },
      },
    ],
  },
  {
    id: "database-bottleneck",
    number: "03",
    users: 100000,
    trafficLabel: "~100K users",
    title: "The bottleneck moves",
    eyebrow: "CONSTRAINT / DATA",
    scenario: "The API tier now scales successfully. More requests reach the database, which is approaching its connection and processing limits.",
    question: "Your APIs are healthy. Why is latency still increasing?",
    principle: "Scaling one tier exposes the next constrained resource. More application servers cannot manufacture database capacity.",
    architecture: { loadBalancer: true, apiInstances: 3 },
    workload: { requestsPerSecond: 2500, readRatio: 0.86, staticShare: 0.2, expensiveWorkShare: 0.07, expensiveWorkMs: 180, geographicFactor: 0.7 },
    metricKeys: ["traffic", "p95", "apiUtil", "dbUtil", "dbConnections", "errorRate"],
    decisions: [
      {
        id: "cache",
        label: "Add Redis",
        effect: "76% read hit rate",
        outcome: "Repeated reads now terminate in memory. Database queries and connection pressure fall immediately.",
        recommended: true,
        patch: { cache: true, cacheHitRate: 0.76 },
        addition: { name: "REDIS CACHE", why: "Repeated reads are overloading the database.", improves: ["Read latency", "Database load", "Read throughput"], costs: ["Cache invalidation", "Stale data", "Memory and operations"] },
      },
      {
        id: "more-api",
        label: "Add more APIs",
        effect: "6 application instances",
        outcome: "API utilisation drops, but the database remains saturated. More callers can even make connection pressure arrive faster.",
        patch: { apiInstances: 6 },
        addition: { name: "MORE API CAPACITY", why: "Application capacity is easy to add.", improves: ["API headroom"], costs: ["Database bottleneck remains", "More connections", "Higher cost"] },
      },
      {
        id: "queue-db-stage",
        label: "Add a queue",
        effect: "Async workers absorb jobs",
        outcome: "Background work is decoupled, but ordinary reads still reach the overloaded database synchronously.",
        patch: { queue: true, workers: 3 },
        addition: { name: "MESSAGE QUEUE", why: "Some work can happen later.", improves: ["Background task isolation"], costs: ["Read bottleneck remains", "Retries", "Backpressure"] },
      },
      {
        id: "vertical-db",
        label: "Upgrade database",
        effect: "1.75× primary capacity",
        outcome: "Vertical scaling buys real headroom and may be the simplest operational choice, but the ceiling and single-primary risk remain.",
        patch: { databaseCapacity: 2800, connectionLimit: 1000 },
        addition: { name: "LARGER PRIMARY", why: "The current database is capacity-bound.", improves: ["Immediate DB headroom", "Operational simplicity"], costs: ["Finite ceiling", "Larger blast radius", "Higher unit cost"] },
      },
    ],
    checkpoint: {
      question: "Why didn't adding more API capacity remove the latency spike?",
      options: [
        { id: "db", label: "The database stayed saturated", correct: true, explanation: "Exactly. Capacity added above a bottleneck does not increase the constrained tier's throughput." },
        { id: "network", label: "The browser became slower", explanation: "The measured pressure is inside the data tier, not the client network." },
        { id: "packets", label: "There were too few animations", explanation: "Packets represent traffic; they do not create capacity." },
      ],
    },
  },
  {
    id: "read-scaling",
    number: "04",
    users: 250000,
    trafficLabel: "~250K users",
    title: "Scale the read path",
    eyebrow: "CONSTRAINT / READS",
    scenario: "Caching removed repeated work, but a larger read-heavy workload now pushes uncached reads back toward the primary database.",
    question: "How should read capacity grow without sending every read to the primary?",
    principle: "Separate read capacity from the write authority when the workload and consistency requirements allow it.",
    architecture: { loadBalancer: true, apiInstances: 7, cache: true, cacheHitRate: 0.76 },
    workload: { requestsPerSecond: 8000, readRatio: 0.92, staticShare: 0.24, expensiveWorkShare: 0.08, expensiveWorkMs: 190, geographicFactor: 0.9 },
    metricKeys: ["traffic", "p95", "primaryUtil", "replicaUtil", "cacheHit", "replicationLag"],
    decisions: [
      {
        id: "replicas",
        label: "Add read replicas",
        effect: "2 read replicas",
        outcome: "Writes remain on the primary while most uncached reads spread across replicas. Read throughput grows, with a small consistency window.",
        recommended: true,
        patch: { replicas: 2 },
        addition: { name: "READ REPLICAS", why: "Uncached reads are saturating the primary database.", improves: ["Read throughput", "Primary headroom", "Read availability"], costs: ["Replication lag", "Read routing", "More database nodes"] },
      },
      {
        id: "larger-cache",
        label: "Increase cache coverage",
        effect: "90% read hit rate",
        outcome: "A larger cache can be very effective for cacheable reads, but cold, personalised, or strongly consistent reads still need a database path.",
        patch: { cacheHitRate: 0.9 },
        addition: { name: "LARGER CACHE", why: "More reads can avoid storage.", improves: ["Hot-read latency", "Primary load"], costs: ["More memory", "Invalidation surface", "Cold reads remain"] },
      },
      {
        id: "bigger-primary",
        label: "Upgrade primary",
        effect: "1.9× primary capacity",
        outcome: "The primary gains headroom without consistency lag, but all reads and writes still share one scaling and failure boundary.",
        patch: { databaseCapacity: 3040, connectionLimit: 1000 },
        addition: { name: "LARGER PRIMARY", why: "One database handles all reads and writes.", improves: ["Simple consistency", "Immediate capacity"], costs: ["Finite ceiling", "Shared failure boundary", "Premium hardware"] },
      },
      {
        id: "shard-reads",
        label: "Shard the data",
        effect: "2 data partitions",
        outcome: "Sharding can distribute load, but it introduces routing and cross-shard complexity before the simpler read/write split is exhausted.",
        patch: { shards: 2 },
        addition: { name: "EARLY SHARDING", why: "Partitions distribute data and load.", improves: ["Aggregate capacity", "Dataset size ceiling"], costs: ["Routing complexity", "Cross-shard queries", "Rebalancing"] },
      },
    ],
    checkpoint: {
      question: "Why can a replica briefly return an older value?",
      options: [
        { id: "async-copy", label: "Changes arrive asynchronously", correct: true, explanation: "Right. The primary commits first; replicas apply that change shortly afterwards." },
        { id: "cache-bug", label: "Redis deleted the write", explanation: "The consistency window here is between the primary and its replicas." },
        { id: "slow-client", label: "The client clock is slow", explanation: "Client time does not control replication progress." },
      ],
    },
  },
  {
    id: "global-static",
    number: "05",
    users: 500000,
    trafficLabel: "~500K users",
    title: "Move bytes closer",
    eyebrow: "CONSTRAINT / DISTANCE",
    scenario: "Users are now geographically distributed and static images, JavaScript, CSS, and media still travel from the origin region.",
    question: "How do you reduce distance and origin work for cacheable static content?",
    principle: "Network distance is a constraint too. Cache the right bytes near the people requesting them.",
    architecture: { loadBalancer: true, apiInstances: 8, cache: true, cacheHitRate: 0.78, replicas: 2 },
    workload: { requestsPerSecond: 10000, readRatio: 0.88, staticShare: 0.42, expensiveWorkShare: 0.08, expensiveWorkMs: 190, geographicFactor: 1.8 },
    metricKeys: ["traffic", "p95", "edgeLatency", "originTraffic", "cdnHit", "bandwidth"],
    decisions: [
      {
        id: "cdn",
        label: "Add a CDN edge",
        effect: "86% static hit rate",
        outcome: "Most static requests terminate at a nearby edge. Origin traffic, bandwidth, and distant-user latency all fall.",
        recommended: true,
        patch: { cdn: true, cdnHitRate: 0.86 },
        addition: { name: "CDN EDGE", why: "Distant users repeatedly fetch cacheable bytes from one origin.", improves: ["Static latency", "Origin traffic", "Bandwidth pressure"], costs: ["Purge strategy", "Cache correctness", "Provider dependency"] },
      },
      {
        id: "second-origin",
        label: "Add another region",
        effect: "2 origin regions",
        outcome: "A second origin shortens some paths and improves resilience, but every static hit still consumes origin compute and bandwidth.",
        patch: { originRegions: 2 },
        addition: { name: "SECOND ORIGIN", why: "Users are far from the original region.", improves: ["Regional latency", "Regional resilience"], costs: ["Data coordination", "Double operations", "Static traffic remains"] },
      },
      {
        id: "compress",
        label: "Compress assets",
        effect: "32% fewer bytes",
        outcome: "Compression is a strong baseline optimisation. It reduces transfer size, but requests still travel to and load the origin.",
        patch: { compressionRatio: 0.68 },
        addition: { name: "ASSET COMPRESSION", why: "Static payloads consume bandwidth.", improves: ["Transfer size", "Download time"], costs: ["Origin distance remains", "Build complexity"] },
      },
      {
        id: "global-api",
        label: "Add API instances",
        effect: "12 API instances",
        outcome: "Application compute grows, but a user far from the origin still pays the network round trip for every static asset.",
        patch: { apiInstances: 12 },
        addition: { name: "MORE ORIGIN COMPUTE", why: "The origin can accept more traffic.", improves: ["Origin headroom"], costs: ["Distance unchanged", "Bandwidth unchanged", "Higher cost"] },
      },
    ],
  },
  {
    id: "asynchronous-work",
    number: "06",
    users: 1000000,
    trafficLabel: "~1M users",
    title: "Get work off the request path",
    eyebrow: "CONSTRAINT / TIME",
    scenario: "Account creation now waits for a database write, email, analytics, and thumbnail generation before returning a response.",
    question: "Why should the user wait for work that can finish later?",
    principle: "Keep the synchronous path as small as the product promise allows; decouple the rest behind durable work.",
    architecture: { loadBalancer: true, apiInstances: 10, cache: true, cacheHitRate: 0.8, replicas: 2, cdn: true, cdnHitRate: 0.86 },
    workload: { requestsPerSecond: 14000, readRatio: 0.9, staticShare: 0.35, expensiveWorkShare: 0.28, expensiveWorkMs: 620, geographicFactor: 1.9 },
    metricKeys: ["traffic", "p95", "errorRate", "queueDepth", "throughput", "apiUtil"],
    decisions: [
      {
        id: "queue",
        label: "Add a message queue",
        effect: "4 background workers",
        outcome: "The API acknowledges quickly, while independently scaled workers process email, analytics, and thumbnails with retries.",
        recommended: true,
        patch: { queue: true, workers: 4 },
        addition: { name: "MESSAGE QUEUE", why: "Expensive side effects are blocking the user-facing request.", improves: ["Response latency", "Failure isolation", "Burst handling"], costs: ["Retries and idempotency", "Queue depth", "Eventual completion"] },
      },
      {
        id: "more-api-async",
        label: "Add more APIs",
        effect: "16 API instances",
        outcome: "More concurrent requests can begin, but every one still waits for email, analytics, and image processing to finish.",
        patch: { apiInstances: 16 },
        addition: { name: "MORE API CAPACITY", why: "Concurrency has increased.", improves: ["Request concurrency"], costs: ["Slow critical path remains", "More cost", "Downstream pressure"] },
      },
      {
        id: "faster-db-async",
        label: "Upgrade database",
        effect: "1.75× DB capacity",
        outcome: "The write is faster, but email, analytics, and thumbnail latency still accumulate inside the response.",
        patch: { databaseCapacity: 2800 },
        addition: { name: "FASTER DATABASE", why: "One synchronous step becomes faster.", improves: ["Write latency"], costs: ["Other blocking work remains", "Higher database cost"] },
      },
      {
        id: "inline-workers",
        label: "Optimise each task",
        effect: "45% faster side effects",
        outcome: "Optimisation helps, but independent failures and latency remain coupled to the request. The architecture still waits for everything.",
        patch: { syncWorkMultiplier: 0.55 },
        addition: { name: "INLINE OPTIMISATION", why: "Each blocking task can run faster.", improves: ["Median latency"], costs: ["Failure coupling remains", "Long-tail latency", "Limited burst absorption"] },
      },
    ],
    checkpoint: {
      question: "Why acknowledge before email delivery finishes?",
      options: [
        { id: "decouple", label: "Email is not required for the account commit", correct: true, explanation: "Exactly. Durable queued work can retry without extending or failing the account-creation request." },
        { id: "ignore", label: "Email does not matter", explanation: "It still matters; it simply has a different completion and retry contract." },
        { id: "hide", label: "It makes the metric look better", explanation: "The goal is a smaller product-critical path, not cosmetic reporting." },
      ],
    },
  },
  {
    id: "failure",
    number: "07",
    users: 1000000,
    trafficLabel: "~1M users",
    title: "Prove the redundancy",
    eyebrow: "CONSTRAINT / FAILURE",
    scenario: "The system has enough capacity. Now remove one live API instance and observe whether earlier architectural choices preserve availability.",
    question: "What happens when API 2 disappears?",
    principle: "Scalability work often creates reliability options. Redundancy only matters when routing and health checks use it.",
    architecture: { loadBalancer: true, apiInstances: 10, cache: true, cacheHitRate: 0.8, replicas: 2, cdn: true, cdnHitRate: 0.86, queue: true, workers: 4 },
    workload: { requestsPerSecond: 14000, readRatio: 0.9, staticShare: 0.35, expensiveWorkShare: 0.28, expensiveWorkMs: 620, geographicFactor: 1.9 },
    metricKeys: ["traffic", "p95", "errorRate", "apiUtil", "throughput", "availability"],
    addition: {
      name: "REDUNDANCY UNDER TEST",
      why: "Failure is inevitable; availability depends on healthy alternatives and routing.",
      improves: ["Confidence", "Fault isolation", "Recovery practice"],
      costs: ["Spare capacity", "Health-check design", "Failure testing"] ,
    },
    checkpoint: {
      question: "Why does the service remain available after one API fails?",
      options: [
        { id: "reroute", label: "The load balancer routes to healthy instances", correct: true, explanation: "Correct. Redundant stateless instances provide somewhere safe for the load balancer to send new requests." },
        { id: "redis-api", label: "Redis becomes the API", explanation: "Redis still serves cached data; it does not replace application request handling." },
        { id: "replica-api", label: "A read replica runs the application", explanation: "Database replicas serve reads, not application code." },
      ],
    },
  },
];

export const recommendedDecision = (stage) => stage.decisions?.find((decision) => decision.recommended);
